<div class="col-xl-12 col-lg-8">
   <div class="main-content p-a-2" style="padding-bottom:50px !important;">
        <?php
            if (isset($message))
            {
                // if there are success/error/warning messages, they will be displayed here
                echo $message;
            }
        ?>
		<?php
        if (!($_SERVER['REQUEST_METHOD'] === 'POST')) {
        ?>
        <h1><?php echo __('Dpa'); ?></h1>
        <div style="position: relative; padding-top: 56.25%;">
        	<iframe src="/dpa/pdf" frameborder="0" allowfullscreen
    style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"><?php echo __('iframe error'); ?></iframe>
        </div>
        <br>
        <a href="/dpa/pdf" target="_blank" style="font-size: 15px;"><i class="fa fa-download"></i>&nbsp;&nbsp;<?=__('open pdf')?></a>
    <br><br>
	<form method="POST">
			<input type="checkbox" name="agree" <?php
			if ($preference == true) {
				?>checked disabled<?php
			}?> required>&nbsp;&nbsp;<?php echo __('agree to dpa'); ?>
			<br><br>
			<?php
			if ($preference == false) {
				?><input type="submit" class="form-control btn btn-primary pull-right"><?php
			}?>
	</form>
	<?php
	}
	?>
    </div>
</div>
